<?php
    require_once('util/main.php');
    require_once('util/database.php');
?>
<!DOCTYPE html>
<!--
    Created by: Chris Jarrett
-->
<html>
    <head>
        <title>GearShare</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>

        <link rel="stylesheet/less" type="text/css" href="css/style.less">
        <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/3.7.1/less.min.js" ></script>
        <!--<script src="less.js" type="text/javascript"></script>-->

    </head>

    <body>
        <div class="container-fluid header">            
            <h1 style="font-weight: bolder; font-size: 5vw"><a id="logo" href="index.php">GearShare</a></h1>
                <h3 style="font-size: 3vw">Outdoor Equipment and Trip Management</h3>
        </div>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>                        
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="index.php">News</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Gear
                                <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="findgear.php">Find Gear</a></li>
                                <li><a href="mygear.php">My Gear</a></li>
                            </ul>
                        </li>
                        <li><a href="trips.html">Trips</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">GearShare
                                Account
                                <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <?php
                                if (isset($_SESSION['user'])) :
                                ?>
                                    <li><a href="<?php echo 'myaccount.php'; ?>">My Account</a></li>
                                    <li><a href="<?php echo 'accountProcess.php?action=logout'; ?>">Logout</a>
                                <?php else: ?>
                                    <li><a href="<?php echo 'accountProcess.php' ?>">Login/Register</a></li>
                                <?php endif; ?>
                            </ul>
                        </li>
                        <?php 
                            if(isset($_SESSION['user'])) {
                            if($_SESSION['user']['access_level'] == 'admin') {
                            echo '<li><a href="adminUsers.php">Admin Control Panel</a></li>';
                        }
                            }
                        ?>
                    </ul>
                </div>
            </div>
        </nav>
        
        <!--This will be generated by accessing the server's blog feed-->
        <div class="container-fluid">
            <h4 style="font-weight: bold;">Upcoming Event! - Roulette Rapids - Friday, September 21</h4>
            <p>
            Charity Event for child gambling addicts. Take a chance on these kids.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Nam semper fermentum lacus,</br>
            faucibus blandit massa feugiat vel. Etiam quis odio at augue consectetur
            iaculis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
            
            </br>
            
            <h4 style="font-weight: bold;">Upcoming Event! - Latin on the River - Friday, September 2</h4>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam semper 
            fermentum lacus, faucibus blandit massa feugiat vel. Etiam quis 
            odio at augue consectetur iaculis.</br> Lorem ipsum dolor sit amet, 
            consectetur adipiscing elit.

 
            </p>
        </div>
    </body>
</html>
